# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd36b1030ed338534f80182d779f51c292ef55175e1378ee2a2d39fbbb223a06ba4670c023b0ffbd1cf5157032f5acecff0fe5b9a88d6bc0189f873cd62572e1

test:
  secret_key_base: 9c90b6820c2d4b6ba596e8b63c21e57ba667de7092d9936a2b30f4f747cf59769f91e51aa79f01cb38c85c08ad11d8fcc091e569609804dbe05054afb0e37580

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
